services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file:
      - .env.production
    volumes:
      - ./staticfiles:/app/staticfiles
    command: /app/entrypoint.sh
